function [dxdt] = derivative (t,x,p,u,indS)
% Derivative for the reaction model ODEMEXwscore

    s0 = p(indS.p.s0);
   vt = p(indS.p.vt);
   we = p(indS.p.we);
   wr = p(indS.p.wr);
   wp = p(indS.p.wp);
   wq = p(indS.p.wq);
   thetar = p(indS.p.thetar);
   thetax = p(indS.p.thetax);
   nr = p(indS.p.nr);
   nx = p(indS.p.nx);
   gmax = p(indS.p.gmax);
   Kp = p(indS.p.Kp);
   vm = p(indS.p.vm);
   Km = p(indS.p.Km);
   ns = p(indS.p.ns);
   kq = p(indS.p.kq);
   Kt = p(indS.p.Kt);
   nq = p(indS.p.nq);
   cl = p(indS.p.cl);
   k_cm = p(indS.p.k_cm);
   b = p(indS.p.b);
   dm = p(indS.p.dm);
   kb = p(indS.p.kb);
   ku = p(indS.p.ku);
   M = p(indS.p.M);

   si = x(indS.s.si);
   a = x(indS.s.a);
   r = x(indS.s.r);
   mm = x(indS.s.mm);
   mp = x(indS.s.mp);
   mq = x(indS.s.mq);
   mr = x(indS.s.mr);
   mt = x(indS.s.mt);
   rmm = x(indS.s.rmm);
   rmp = x(indS.s.rmp);
   rmq = x(indS.s.rmq);
   rmr = x(indS.s.rmr);
   rmt = x(indS.s.rmt);
   zmm = x(indS.s.zmm);
   zmr = x(indS.s.zmr);
   zmp = x(indS.s.zmp);
   zmq = x(indS.s.zmq);
   zmt = x(indS.s.zmt);
   em = x(indS.s.em);
   et = x(indS.s.et);
   ep = x(indS.s.ep);
   Q = x(indS.s.Q);

   f = cl*k_cm;
   Kg = gmax/Kp;
   gam = gmax*a/(Kg+a);
   ttrate = (rmq+rmr+rmp+rmt+rmm)*gam;
   lam = ttrate/M;
   Mdyn = (nr*(r+rmr+rmp+rmt+rmm+rmq+zmr+zmp+zmt+zmm+zmq)+nx*(ep+Q+et+em));
   Rmass = (nr*(rmr+zmr)+nx*(mp+mq+mt+mm+rmp+rmt+rmm+rmq+zmp+zmt+zmm+zmq))/3;
   fr = nr*(r+rmr+rmp+rmt+rmm+rmq+zmr+zmp+zmt+zmm+zmq)/Mdyn;
   nuimp = et*vt*s0/(Kt+s0);
   nucat = em*vm*si/(Km+si);


   dxdt(indS.s.si) = 0 +1*(nuimp) -1*(nucat) -1*(lam*si);%   si
   dxdt(indS.s.a) = 0 +1*(ns*nucat) -1*(ttrate) -1*(lam*a);%   a
   dxdt(indS.s.r) = 0 -1*(kb*r*mm) +1*(ku*rmm) -1*(kb*r*mp) +1*(ku*rmp) -1*(kb*r*mq) +1*(ku*rmq) -1*(kb*r*mr) +1*(ku*rmr) -1*(kb*r*mt) +1*(ku*rmt) +1*((gam/nx)*rmm) +1*((gam/nx)*rmp) +1*((gam/nx)*rmq) +2*((gam/nr)*rmr) +1*((gam/nx)*rmt) -1*(lam*r);%   r
   dxdt(indS.s.mm) = 0 +1*(we*a/(thetax+a)) -1*(kb*r*mm) +1*(ku*rmm) +1*((gam/nx)*rmm) -1*(dm*mm) -1*(lam*mm);%   mm
   dxdt(indS.s.mp) = 0 +1*(wp*a/(thetax+a)) -1*(kb*r*mp) +1*(ku*rmp) +1*((gam/nx)*rmp) -1*(dm*mp) -1*(lam*mp);%   mp
   dxdt(indS.s.mq) = 0 +1*((wq*a/(thetax+a))/(1+pow((Q/kq),nq))) -1*(kb*r*mq) +1*(ku*rmq) +1*((gam/nx)*rmq) -1*(dm*mq) -1*(lam*mq);%   mq
   dxdt(indS.s.mr) = 0 +1*(wr*a/(thetar+a)) -1*(kb*r*mr) +1*(ku*rmr) +1*((gam/nr)*rmr) -1*(dm*mr) -1*(lam*mr);%   mr
   dxdt(indS.s.mt) = 0 +1*(we*a/(thetax+a)) -1*(kb*r*mt) +1*(ku*rmt) +1*((gam/nx)*rmt) -1*(dm*mt) -1*(lam*mt);%   mt
   dxdt(indS.s.rmm) = 0 +1*(kb*r*mm) -1*(ku*rmm) -1*(f*rmm) +1*(b*zmm) -1*((gam/nx)*rmm) -1*(lam*rmm);%   rmm
   dxdt(indS.s.rmp) = 0 +1*(kb*r*mp) -1*(ku*rmp) -1*(f*rmp) +1*(b*zmp) -1*((gam/nx)*rmp) -1*(lam*rmp);%   rmp
   dxdt(indS.s.rmq) = 0 +1*(kb*r*mq) -1*(ku*rmq) -1*(f*rmq) +1*(b*zmq) -1*((gam/nx)*rmq) -1*(lam*rmq);%   rmq
   dxdt(indS.s.rmr) = 0 +1*(kb*r*mr) -1*(ku*rmr) -1*(f*rmr) +1*(b*zmr) -1*((gam/nr)*rmr) -1*(lam*rmr);%   rmr
   dxdt(indS.s.rmt) = 0 +1*(kb*r*mt) -1*(ku*rmt) -1*(f*rmt) +1*(b*zmt) -1*((gam/nx)*rmt) -1*(lam*rmt);%   rmt
   dxdt(indS.s.zmm) = 0 +1*(f*rmm) -1*(b*zmm) -1*(lam*zmm);%   zmm
   dxdt(indS.s.zmr) = 0 +1*(f*rmr) -1*(b*zmr) -1*(lam*zmr);%   zmr
   dxdt(indS.s.zmp) = 0 +1*(f*rmp) -1*(b*zmp) -1*(lam*zmp);%   zmp
   dxdt(indS.s.zmq) = 0 +1*(f*rmq) -1*(b*zmq) -1*(lam*zmq);%   zmq
   dxdt(indS.s.zmt) = 0 +1*(f*rmt) -1*(b*zmt) -1*(lam*zmt);%   zmt
   dxdt(indS.s.em) = 0 +1*((gam/nx)*rmm) -1*(lam*em);%   em
   dxdt(indS.s.et) = 0 +1*((gam/nx)*rmt) -1*(lam*et);%   et
   dxdt(indS.s.ep) = 0 +1*((gam/nx)*rmp) -1*(lam*ep);%   ep
   dxdt(indS.s.Q) = 0 +1*((gam/nx)*rmq) -1*(lam*Q);%   Q
   dxdt = dxdt(:);

