# Example for documentation test3.job
MODEL      rna2.rxnm      # model location
SETDIST	   G10:poiss10.dat
SETDIST	   G20:poiss20.dat
SETCORR	   G10,G20:0.6
OUTFOLDER  outs3/          # where 
DOT        1              # Make a diagram of the model
NAME       doc3
OBSERVE    G10,G20,M1,M2
TYPE       DET
DETPOINTS  0:100:100000
TYPE       ST
STNREP     5
STTPOINTS  0:1000:100000
TYPE       SS
SSNREP     2000
SSTPOINTS  500000
SCATTER    G10,G20
SCATTER    M1,M2
